### ISSUE TITLE
Convert Electronic Circuit Writeup To Latex?

### ISSUE THREAD

**Issue by iShauny** [benzoferrari123/pinerf#3]
Perhaps for github readability, the PDF detailing the circuit design should be converted to a LaTeX file

**Comment by aBen10** [comment]
I converted and submitted but doesn't do anything for readability. Kept the pdf

**Comment by iShauny** [comment]
PDF is fine, then. do you have an editable version of the circuit in a spice diagram like MULTISIM that can be downloaded? any work on a PCB design?

**Comment by iShauny** [comment]
gonna open this as a new issue actually

**Comment by aBen10** [comment]
Sure, can get to that next week
