### ISSUE TITLE
PCB Design/Spice Simulation

### ISSUE THREAD

**Issue by iShauny** [benzoferrari123/pinerf#8]

**Comment by iShauny** [comment]
any progress?

**Comment by aBen10** [comment]
Yes, I got software downloaded. It shouldn't take long to do. Should be able to get to it Thursday

**Comment by iShauny** [comment]
hows it going?

**Comment by aBen10** [comment]
Have it all set up. Just need to figure out the simulation with multiple gnd references. I'll have it done, but currently focusing on an autonomous systems term project due this week.
